[template]
src = "haproxy.cfg.tmpl"
dest = "/etc/haproxy/haproxy.cfg"
owner = "root"
group = "root"
mode = "0644"
keys = ["/app"]
check_cmd = "/usr/sbin/haproxy -c -q -f {{ .src }}"
reload_cmd = "/usr/sbin/haproxy -f {{ .src }} -p /var/run/haproxy.pid -sf $(</var/run/haproxy.pid)"
